### ISSUE TITLE
No "issues" on Android repo, so how can I file a bug?

### ISSUE THREAD

**Issue by ghost** [google/santa-tracker-web#1]
Since 1st Dec update, "Memory" on Android is unplayable as it constantly freezes. 
Pause still works, but no doors can be opened after a few seconds.
How come there's no issue tracker for the Android version on github :(

**Comment by samthor** [comment]
@samtstern

**Comment by samtstern** [comment]
@digitaltoast we don't currently have a bug tracker but I read all of the Play Store reviews!  We will open the issues once the 2016 source is live.

I saw a number of users with this issue on the Memory game and I believe you should see the bug fixed in version `4.0.12` which came out last week.

**Comment by ghost** [comment]
Well, it doesn't freeze, but it still behaves oddly - at the same point as it used to freeze, doors close with weird timings. Not sure what was wrong with the previous version which worked.
