### ISSUE TITLE
Open Source assets?

### ISSUE THREAD

**Issue by AaronLayton** [google/santa-tracker-web#1145]
@ebidel any chance we can get all the original Art assets open sources for this project aswell? 

I am looking through the commit logs and can see when images are being committed but it doesn't give us any insights into the build process from turning a mock up into the real thing

**Comment by ebidel** [comment]
Should be all there.  Village for example lives alongside the element: https://github.com/google/santa-tracker-web/tree/master/scenes/village/img. Assets are CC-BY-NC: https://github.com/google/santa-tracker-web/blob/master/LICENSE

We have no plans to OS illustrator files, if that's what you mean.

**Comment by AaronLayton** [comment]
Yeah that's what I meant - shame would have been good aswell

**Comment by ebidel** [comment]
Most of the assets are SVG. You _could_ go to town ):

**Comment by AaronLayton** [comment]
Hahaha - great work anyway, thanks @ebidel
