### ISSUE TITLE
Polymer 2.x release

### ISSUE THREAD

**Issue by xylomo** [google/santa-tracker-web#12]
I have been following along with the Santa Tracker playlist that's available via YouTube. The Santa Tracker web app has been a huge help for me learning the Polymer ecosystem.

I was just curious if the 2017 Santa Tracker version was going to be released like the previous years?

**Comment by samthor** [comment]
I'm glad you're excited to learn Polymer.

Unfortunately there are some roadblocks which meant we have not yet set a date for the release and I can't share any timelines. I'll update this bug when we have news.

**Comment by xylomo** [comment]
Okay, sounds good. Thanks for your videos. They've been really helpful. Looking forward to the release
