### ISSUE TITLE
release.js doesn't work on linux, throws a lot of errors and crashes from out of memory

### ISSUE THREAD

**Issue by SleepyBoi2852** [google/santa-tracker-web#158]
**Describe the bug**
When trying to run release.js on Linux, it throws thousands of errors while compiling (too long for vscode to handle so I can't provide a log) and throws a "JavaScript heap out of memory" error when almost done

**To Reproduce**
1. Use Linux
2. Clone Santa Tracker using git
3. Change Directory to Santa Tracker
4. Run `node release.js`
5. Stuff Happens that isn't supposed to happen

**Expected behavior**
It to compile

**Comment by Jezzamonn** [comment]
If you just want to run the game locally, serve.js is the script you want to run!

**Comment by Jezzamonn** [comment]
Yup, there are a lot of warnings during compilation. It's also likely your device doesn't have enough memory to compile everything through that release script.

The script's purpose is to be used by the Santa Tracker team, so it's not really important for it to work outside that.
