### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by baxtmann** [google/santa-tracker-web#16]
Hi, I have seen that this issue has been ressolved in the past, but I am trying to get it working on a new machine (Debian 8), and I am getting the issue again. `670 silly postinstall SantaTracker@2015.0.0
671 info lifecycle SantaTracker@2015.0.0~postinstall: SantaTracker@2015.0.0
672 verbose lifecycle SantaTracker@2015.0.0~postinstall: unsafe-perm in lifecycle true
673 verbose lifecycle SantaTracker@2015.0.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/baxtmann/santa-tracker-web-2016/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
674 verbose lifecycle SantaTracker@2015.0.0~postinstall: CWD: /home/baxtmann/santa-tracker-web-2016
675 silly lifecycle SantaTracker@2015.0.0~postinstall: Args: [ '-c', 'bower install; gulp' ]
676 silly lifecycle SantaTracker@2015.0.0~postinstall: Returned: code: 1  signal: null
677 info lifecycle SantaTracker@2015.0.0~postinstall: Failed to exec postinstall script
678 verbose stack Error: SantaTracker@2015.0.0 postinstall: `bower install; gulp`
678 verbose stack Exit status 1
678 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
678 verbose stack     at EventEmitter.emit (events.js:182:13)
678 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
678 verbose stack     at ChildProcess.emit (events.js:182:13)
678 verbose stack     at maybeClose (internal/child_process.js:978:16)
678 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
679 verbose pkgid SantaTracker@2015.0.0
680 verbose cwd /home/baxtmann/santa-tracker-web-2016
681 verbose Linux 3.16.0-6-amd64
682 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
683 verbose node v11.3.0
684 verbose npm  v6.4.1
685 error code ELIFECYCLE
686 error errno 1
687 error SantaTracker@2015.0.0 postinstall: `bower install; gulp`
687 error Exit status 1
688 error Failed at the SantaTracker@2015.0.0 postinstall script.
688 error This is probably not a problem with npm. There is likely additional logging output above.
689 verbose exit [ 1, true ]
`
From what I can tell, its an issue with the bower install; gulp having some type of install issue, idk what exactly is wrong. 
If you need more info to figure this out, lmk. I have tried installing 4 separate times on separate machines.

**Comment by samthor** [comment]
Hey! Thanks for your interest, but this repo is still the open-sourced version of Santa Tracker from a couple of years ago. I wouldn't try to compile it right now.

**Comment by baxtmann** [comment]
Usually, I would agree, but just yesterday I was able to get it working perfectly on a raspberry pi, so I am just really confused why it won't work on a different machine.

**Comment by baxtmann** [comment]
Are there any plans to release last year's Santa tracker?

**Comment by samthor** [comment]
Unfortunately there's no plans to release the 2017 codebase. However, we plan to release the 2018 codebase early in the new year.

**Comment by BrettPlays** [comment]
Any updates on this?

**Comment by baxtmann** [comment]
As of right now, as far as I can tell, the new codebase has not been released yet. 
@samthor any update on this?

**Comment by samthor** [comment]
Sorry folks. My comment was written before [this happened](https://dev.to/chromiumdev/the-gift-of-giving-up-1lgl).

In 2019, we have a whole-new codebase which we'll hopefully be open-sourcing soon (we plan to do it during Dec).

**Comment by baxtmann** [comment]
@samthor 
Hi Sam, just wondering if we can expect the new codebase this December still - and if so, any idea on when approximately we would be seeing it in December? 
Thanks!

**Comment by BrettPlays** [comment]
> @samthor
> Hi Sam, just wondering if we can expect the new codebase this December still - and if so, any idea on when approximately we would be seeing it in December?
> Thanks!

I’ll bet that it will be released on the site on the 1sr or the 4th and will go public on GitHub on the 24th.

**Comment by baxtmann** [comment]
That's probably the plan - though It would be awesome if we had it before that (like 2nd week of dec). I want to get it running before then so if the new one isn't released I'll just work on getting the old codebase working (if I did it last year I should be able to do it this year!)

**Comment by BrettPlays** [comment]
> That's probably the plan - though It would be awesome if we had it before that (like 2nd week of dec). I want to get it running before then so if the new one isn't released I'll just work on getting the old codebase working (if I did it last year I should be able to do it this year!)

Same, though I tried to get this codebase working by myself and with 2 other people and we were all unsuccessful.

**Comment by BrettPlays** [comment]
> That's probably the plan - though It would be awesome if we had it before that (like 2nd week of dec). I want to get it running before then so if the new one isn't released I'll just work on getting the old codebase working (if I did it last year I should be able to do it this year!)

Just saw something by the lead developer of Santa Tracker (samthor) and he said they will be releasing it in early 2020.

**Comment by samthor** [comment]
👍
