### ISSUE TITLE
The "Learn Codelab" is not working anymore

### ISSUE THREAD

**Issue by danielemaddaluno** [google/santa-tracker-web#19]
The [codelab](https://santatracker.google.com/codelab.html) programming part is not working anymore. The first three levels are ok but when you try to finish the first programming level the interface stucks.

**Comment by danielemaddaluno** [comment]
Does it jump now at level 11?

**Comment by samthor** [comment]
There's a "jump" command that is introduced later, yes.

Can you talk about the failure case you saw on the 3rd level? Your browser version and so on might help. Otherwise I can't reproduce the issue.

**Comment by danielemaddaluno** [comment]
You are right, the level three now is ok!
But can't go on with level 11 in this moment.
It simply does not jump in any direction...

My browser:
> Google Chrome is up to date
> Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by victorjchamorro** [comment]
i agree, level 11 does not work, do not jump. Try the latest version of Firefox and Chrome
