### ISSUE TITLE
Question about API.

### ISSUE THREAD

**Issue by BrettPlays** [google/santa-tracker-web#20]
Wondering where I can find a link to a reliable API where I can get data like the countdown time till the tracker and information on Santa on Christmas eve such as temperature and location.  Though I am curious if it will change for this upcoming 2019 December.

Thank You!

**Comment by baxtmann** [comment]
In regards to Santa location on Christmas eve - Use https://storage.googleapis.com/santa/ to get that type of information. You can find V1 of the flight route and 2018 (v2) of the flight route located there. Chances are this will be changed for 2019 at some point. The V2 version has the temperature as one of the data items - although it is a static value from 2018 Christmas eve (I think)
Cheers!

**Comment by BrettPlays** [comment]
For https://storage.googleapis.com/santa/ do you know how I would go about testing it?  Would simply downloading the file (.xml) and then running the plugin off of that page/file after changing it work?

Also where is the flight path?  I can't seem to find it.

**Comment by baxtmann** [comment]
Sorry - I don't quite understand - what "plugin" are you referring to?  Flight path is the v1/santa_en.json file (v1) or 2018/santa_en.json file. The flight path would be the longitudes and latitudes which you could plot (import) into some type of map api to show the location in realtime. This guide might point you in the right direction for using the santa_en.json file: https://www.jimbobbennett.io/fabulous-santa-tracker/
Cheers!

**Comment by BrettPlays** [comment]
Thank You so much!
For better wording since "plugin" doesn't work, replace it with "application". :)
Thanks again!
