### ISSUE TITLE
When it'll be available the last release?

### ISSUE THREAD

**Issue by crussman** [google/santa-tracker-web#23]
Greetings,

How you can see in the title, I'm wondering if the new release of the source code will be available soon, since I read from another issues in this repo that a new release was planned for early 2020.

I'm sorry if it isn't the place to ask about it, and, thanks in advance for your time!

Regards

**Comment by samthor** [comment]
Sorry for the delay. It's not the best excuse but the COVID situation
messed up my work plans and so open-sourcing Santa Tracker hasn't been high
priority.

I hope to release it in the next couple of weeks.

**Comment by crussman** [comment]
Oh Sam, please, don't excuse for the delay. This situation surprised all of us, so it's totally comprehensible.
I'm advising to a client who's really excited with the new release, but I'm 100% sure that he'll understand it.
Thanks for your response.
Kindest regards

**Comment by Regian24** [comment]
what about now?
