### ISSUE TITLE
Trying to run serve.js on Windows gives me an importUtils error

### ISSUE THREAD

**Issue by SneezingCactus** [google/santa-tracker-web#34]
I'm having a problem when trying to run serve.js. When I attempt to run it, it gives me an error about importUtils being unsupported on Windows. What can I do to fix this?

**Comment by samthor** [comment]
Ah, sorry about this. None of our developers build on Windows (it's a common story) so I forgot about this file.

As we're just using the path library to work with the path parts of URLs (which always have "/" slashes), you could try replacing the path import with:

```js
const path = require('path').posix;
```

**Comment by SneezingCactus** [comment]
Okay, will try this now. Thanks!

**Comment by SneezingCactus** [comment]
I tried this, and it started the page. However, when I try to load the page it gives me an error in the DevTools console saying that http://localhost:8000/src/:config.json gave a 404 error. What could this be for?

**Comment by Felidanger** [comment]
> I tried this, and it started the page. However, when I try to load the page it gives me an error in the DevTools console saying that http://localhost:8000/src/:config.json gave a 404 error. What could this be for?

hey dude i know this is 5 years old and the issue is closed but did you fix this in any way?
