### ISSUE TITLE
"Top Nav" links on Family Guide appear broken

### ISSUE THREAD

**Issue by dh--** [google/santa-tracker-web#38]
**Describe the bug**
Near the top of the Family Guide page is a blue nav menu containing links to Code | Celebrate | Create | etc.

https://santatracker.google.com/familyguide.html

When I click on some of these links, the site reloads the village, instead of jumping to the correct location.

**To Reproduce**
1. Go to 'https://santatracker.google.com/familyguide.html'
2. Click on 'create'

**Expected behavior**
I'm linked to the title "Get inspired and create something'

**Comment by samthor** [comment]
This seems to just be a Safari issue.
