### ISSUE TITLE
Please remove 'Penguin Proof' and 'Out Like a Light' videos

### ISSUE THREAD

**Issue by dh--** [google/santa-tracker-web#48]
Please remove reference to the takeoff videos.

Links appear:
 - In the menu (top left corner)
 - on santatracker.google.com, the second module down the page
 - in family guide

There are four obvious videos on the site. The Museum and Carpool videos are fine. This issue is about Penguin Proof and Out Like a Light.

**Comment by BrettPlays** [comment]
Wait what's wrong with them?

**Comment by dh--** [comment]
Howdy -- Santa's Product Manager here.

Good question - I'm still getting used to posting feature requests publicly. I could have included a bit more context. I'll try to go a bit deeper than normal on this issue, since you asked. :) 

**tl;dr**
There's nothing wrong with these videos. They will continue to exist, but we've decided to highlight different content for 2020.

**Looking behind the curtain a bit...**
Santa Tracker is built in close partnership with a number of teams here at Google. What appears here as a single product actually requires collaboration with dozens of teams, most of which volunteer some time to help provide a fun experience for our users. Scenes, videos or features contributed in any given year are usually the features that our volunteers are super passionate about. As you might imagine, the things that are really exciting in one year, may be less exciting in subsequent years.

**Context for this request**
Each year, we do a quick review with our previous collaborators to see if we're still on track to ship. Sometimes teams who contributed features in past years decide they want to update/change/remove previously contributed features. That's what's happened here.

As we reached out to the folks who helped us create these two videos, they asked that we not feature them on the site this year. Originally we'd been asked to remove all video content, but we narrowed it down to just these two (which is why I added the explicit inclusion/exclusion list in the last two sentences of the original feature request).

**What's different this year**
Well, this issue tracker is a big difference. :)  This year, our dev team thought that it would be nice to show more of the development process by opening our GitHub repo much earlier than we have in years past. I'm still adjusting.

Normally, I'd just email our internal mailing list a "hey, can you pull down foo and bar videos? thanks!"

I will say that these sorts of changes are super common, especially between American Thanksgiving and the first week in December. This particular issue made it into GitHub (I'm trying!) I can think of 6-10 that I sent in the last two weeks via internal chat and email (old habits die hard...).

**What happens next?**
Likely, you'll see a pull request removing references to these videos sometime in the next few days. The videos will continue to exist though. To be honest, I really like both of the videos. They make me laugh every time I watch them. We'll go through the same exercise in 2021. Maybe they will return. Maybe not. We'll see.

I hope this helps a bit.
