### ISSUE TITLE
App not appearing in Play Store.

### ISSUE THREAD

**Issue by BrettPlays** [google/santa-tracker-web#50]
Isn't necessarily a bug or feature request but I've noticed that the app doesn't seem to be appearing in the Android App Store. Not sure if its the same on iOS but I don't own any Apple Productions so I can't say if it is.

**Comment by dh--** [comment]
Thanks for reporting!

Typically, we've launched an Android app around the last week of November. Santa Tracker 2020 will not have a dedicated android app. Mobile users will be able to access most of the app functionality from the website.

So in this case, this is working as intended.

**Comment by samthor** [comment]
If you still have the app installed from previous years then it will continue to work in 2020.
