### ISSUE TITLE
"Take Off" takes you to "Out Like a Light"

### ISSUE THREAD

**Issue by BrettPlays** [google/santa-tracker-web#60]
**Describe the bug**
On the main page, there is the featured game button in the bottom right and today it says "Take Off" which I assume is referring to the video from a while ago. However when you click it, you are taken to "Out Like a Light". Not sure if this is a bug or intentional. 

**To Reproduce**
1. Go to 'santatracker.google.com'
2. Click on 'Featured: Take Off'

**Expected behavior**
You will be taken to the "Out Like a Light" video.

**Screenshots**
https://i.imgur.com/4hfhLxW.png

**Comment by samthor** [comment]
This is actually intentional but a bit muddled. We sort of want the takeoff video to be named consistently but often rotate which one it is behind the scenes.

**Comment by samthor** [comment]
If you'd like to find any older videos on YouTube, there's a number of enterprising folks which have found the videos on the Google and GoogleMaps channels and made playlists. :)
