### ISSUE TITLE
Problems with compiling js

### ISSUE THREAD

**Issue by ajakubo1** [google/santa-tracker-web#7]
While running npm install (and then gulp serve) I get this error:

```bash
~/software/santa-tracker-web$ npm install

> SantaTracker@2015.0.0 postinstall /home/claim/software/santa-tracker-web
> bower install; gulp

bower                     invalid-meta for:/home/claim/software/santa-tracker-web/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
[20:35:39] Using gulpfile ~/software/santa-tracker-web/gulpfile.js
[20:35:39] Starting 'sass'...
[20:35:39] Starting 'compile-santa-api-service'...
[20:35:39] Starting 'compile-scenes'...
[20:35:41] Finished 'sass' after 2.21 s

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: third_party/externs/web-animations-old.js:26: WARNING - Bad type annotation. Unknown type AnimationEffectReadOnlybower 
 * @param {AnimationEffectReadOnly} effect
           ^

0 error(s), 1 warning(s), 96.2% typed
```

Not quite sure how to deal with it :).

Oh btw. during the installation there was one complilation jar file, for which I had to change the name manually - ah - nevermind, I'll open another bug for it.

**Comment by samthor** [comment]
This is because we depend on `web-animations-utils`, but the externs have been moved.

Also, we haven't released the 2016 version of Santa yet - which has this bug fixed. Watch this space.

**Comment by samthor** [comment]
The 2016 version is now released. Try building again! 👍

**Comment by ajakubo1** [comment]
Thanks, @samthor! My daughter can't wait to play :D. 

I'll open another issue in case there's something wrong.
