### ISSUE TITLE
Elf Ski (Holiday Slopes) is broken

### ISSUE THREAD

**Issue by zZapzz** [google/santa-tracker-web#77]
When you launch it on PC it is very small and all the way at the top of the screen. Most people I've asked don't even like the new Holiday Slopes game. It feels very out of place in the village and we would love it if you returned the old Elf Ski. 
![image](https://user-images.githubusercontent.com/48798142/133261517-a1ce8090-7fb0-4e3f-b956-f602eceda81a.png)

**Comment by scheib** [comment]
Old Elf Ski has been restored.
