### ISSUE TITLE
Carpool has no play button on Safari

### ISSUE THREAD

**Issue by srussell10** [google/santa-tracker-web#808]
![screen shot 2014-12-16 at 8 20 56 am](https://cloud.githubusercontent.com/assets/9545412/5456999/7bff2cd2-84fc-11e4-8ae7-760c652cff40.png)

doesn't play, just a static scene. thanks!

**Comment by samthor** [comment]
It appears like the play button sometimes takes a second to load, but it appears for me. Can't repro.
